### ISSUE TITLE
Add jscs and jshint configs to codestyle repo

### ISSUE THREAD

**Issue by isqua** [ymaps/codestyle#10]
Возможно, имеет смысл добавить конфиги для [jshint](https://github.com/jshint/jshint) и [jscs](https://github.com/jscs-dev/node-jscs), отвечающие код-стайлу?

**Comment by zxqfox** [comment]
@ikokostya @alt-j @vtambourine JSCS предполагает, что код на входе будет валидный, и всякие цикломатические сложности. Официальная рекомендация использовать jscs строго после jshint/jslint/eslint/другойlint.

Идею перенести и поддерживать самим пресет для jscs и конфиг для jshint — поддерживаю, для jscs, например, это можно сделать плагином (условно):
```
$ npm i jscs-yandex
```
`.jscsrc`:
```json
{
  "plugins": ["jscs-yandex"],
  "preset": "yandex"
}
```

Для jshint через extends, '.jshintrc':
```
{
  "extends": "./node_modules/jscs-yandex/.jshintrc"
}
```

Это будет много проще, чем прогонять все фиксы через репо jscs: https://github.com/jscs-dev/node-jscs/pull/1154#issuecomment-77859214, так что я за ;-)

/cc @markelog

**Comment by isqua** [comment]
@zxqfox :+1:

**Comment by markelog** [comment]
Иметь опубликованный jshint конфиг очень удобно, но я не уверен что ему место именно в этом репозитории.

> .jscsrc:

С новыми изменениями достаточно будет только - 

```js
{
	"preset": "jscs-yandex" // чуть позже, можно будет просто "yandex"
}
```

> чем прогонять все фиксы через репо jscs: jscs-dev/node-jscs#1154 (comment), так что я за ;-)

В этом нет ничего странного, применимо ко всем поддерживаемым стайлам, когда приходит запрос на изменение пресета, нужно получить подтверждение у создателей; с Гуглом, Крокфордом, airbnb, etc; со всеми разговариваем.

Я бы не исключал этот пресет из поставки jscs, удобно и способствует его популяризации. Но можно вынести в отдельный модуль, а у jscs он был бы в зависимостях, тогда это был бы просто перевод отвественности - с "нас" на "вас", а для конечного пользователя ничего бы не изменилось.

**Comment by zxqfox** [comment]
> но я не уверен что ему место именно в этом репозитории.

Вопрос больше политический или идеологический. Скорее, соглашусь, что здесь будет свалка, если все конфиги для всех языков суда складывать.

> тогда это был бы просто перевод отвественности - с "нас" на "вас", а для конечного пользователя ничего бы не изменилось.

:+1: Это даже проще, чем выносить и перекладывать на пользователя необходимость отдельно подключать стиль.

**Comment by ikokostya** [comment]
По аналогии с https://github.com/wikimedia/jscs-preset-wikimedia я создал отдельный npm модуль для yandex preset'а https://github.com/ikokostya/jscs-preset-yandex.

Предлагаю перенести его в организацию `yandex` (сам перенести не могу, потому что в ней не состою). После этого я смогу сделать pull request на выпиливание пресета из репозитория `jscs`.

**Comment by markelog** [comment]
@ikokostya можешь, посмотри последний пост в этушке в клубе "разработка интерфейсов" (или как то так, не помню уже).

**Comment by ikokostya** [comment]
Мы добавили настройки для `eslint` и `jscs`. Думаю issue можно закрыть.
