### ISSUE TITLE
`var` block

### ISSUE THREAD

**Issue by twirl** [ymaps/codestyle#14]
We prefer using single `var` block at the beginning of function or block. Like that:
```
var x = 'a',
    y = {
        z: 'x'
    };
```
Our arguments are:
(a) first of all, our code style says, that all function arguments casting and default values assigning must be done at the beginning of the function, like that:
```
function addEvent (options) {
    var type = Array.isArray(options.type) ? options.type: [ options.type ],
        context = options.context || null;
}
```
That, obviously, greatly increases readability and decreases risks of making casting errors.
(b) in second, every variable must be initialized.
This explicitly leads to an idea of having `variables initialization` block. There is no such construction in JavaScript, so we use single `var` to denote such block (note that we add additional indent to any objects/functions declared inside `var` block.

As for requirement to declare variables at the point when they're used first time, this is, in our opinion, bad architectural principle. Partly because of (a) rule, since you can't easily check whether every variable is initialized without reading entire function through, but mostly because such code is obviously under-normalized:
```
var x = 'a';
// code
// block
// no. 1
var y = 'b';
// code
// block
// no. 2
```
Obviously, such function must be split into two different functions comprising block no. 1 and block no. 2 respectively.

So, our suggestion is:
1) replace 'desclare-at-usage-point' principle with a requirement to declare and initialize every variable at the beginning of function or block;
2) use single var + additional indent to outline variable declarations block.

**Comment by ikokostya** [comment]
> It doesn't break backward compatibility

Actually it breaks bc in `yandex` preset in jscs.

**Comment by ikokostya** [comment]
@dfilatov 

> Multiple var do nothing valuable just adding a redundant noise.

Both styles have cons and pros
http://www.2ality.com/2012/11/var-statement-rules.html
http://benalman.com/news/2012/05/multiple-var-statements-javascript/

**Comment by tarmolov** [comment]
Multiple var is becoming more and more popular ^^
https://github.com/npm/npm/commit/7feb52ecc84f1f7f431f9933b39c932f1d24bde6

**Comment by dfilatov** [comment]
@tarmolov It's just because everything is better than "comma-first" style )

**Comment by ascheglov** [comment]
Did you take into account that such code style leads to huge diffs and merge conflicts which cannot be resolved automatically?

```
- var a = 0;      |    
+ var a = 0,      |
      b = 0;      |
                  |
  a = f();        |    var a = f();
+ b = g(a);       |  + var b = g(a);
```

**Comment by twirl** [comment]
@ascheglov Yep, see https://github.com/ymaps/codestyle/issues/14#issuecomment-68041238

**Comment by ikokostya** [comment]
So, majority of the participants disagreed to the proposal and I don't see important advantages.

**Comment by ikokostya** [comment]
Airbnb uses same rule https://github.com/airbnb/javascript#13.2 :wink:
