### ISSUE TITLE
Checking whether variable is undefined

### ISSUE THREAD

**Issue by twirl** [ymaps/codestyle#15]
Not everyone is so happy to be able to assume that global `undefined` is untouched by user.
I suggest to change `undefined` checking to `typeof x == 'undefined'` since it's just safer.

**Comment by ikokostya** [comment]
> This rule does exactly the same sense as explicit type conversions via Boolean, Number, String, etc.

This is not true for `null`. `typeof null === 'object``. I don't see difference between `null` and `undefined` in this case.

**Comment by twirl** [comment]
`typeof null` is the most famous example of JavaScript design flaw. In ES6 Type(null) == 'null'

**Comment by ikokostya** [comment]
In `es6` `typeof null` returns `'object'` http://people.mozilla.org/~jorendorff/es6-draft.html#sec-typeof-operator-runtime-semantics-evaluation

**Comment by twirl** [comment]
Of course, because of backwards compatibility.

**Comment by ikokostya** [comment]
http://es-discourse.com/t/why-typeof-is-no-longer-safe/15
