### ISSUE TITLE
LF at the End of File

### ISSUE THREAD

**Issue by twirl** [ymaps/codestyle#20]
Why using this rule in 2014?
Are you still making one large js file with `cat`?

**Comment by dmikis** [comment]
My final suggestion is to keep this rule if we OK with unix and cli specific aspect in the codestyle. If we do not want to state this, it's may be worth to remove the rule. Also it applies to no-BOM and LF-only rules.

**Comment by tarmolov** [comment]
I agree with @dmikis. Keep it.

**Comment by twirl** [comment]
Okay. So, who makes final decision?

**Comment by alt-j** [comment]
I think @ikokostya must, because he is primary author of this codestyle.

**Comment by twirl** [comment]
Hmm. Does @ikokostya act on behalf of all Yandex JavaScript developers?

**Comment by vtambourine** [comment]
@dmikis, @tarmolov and me voted for keeping the rule. @dodev wasn't so explicit, but he said "I think EOL in the end of file is a good rule to follow", so I will count him on that side :)
@twirl and @zloylos voted for removing the rule.
@alt-j suspends.

So, majority of participants of that discussion supports that rule. This issue can be closed.

**Comment by tarmolov** [comment]
Don't hurry, please ;)

**Comment by zxqfox** [comment]
@twirl I'm not sure why you against this.

Pros:
- POSIX tools that requires EOL at EOF (e.g. git) wouldn't warn you and throw an error;
- Explicit (require last EOL) is better than implicit (allow both variants);
- Diffs would contain less noise;
- EOL at EOF also guarantees that every line in file will be ended with EOL that simplifies parsing a little;
- Your variants here.

Cons:
- Need to configure `.editorconfig` file and install plugin for your IDE (you working in notepad, right?)?

**Comment by twirl** [comment]
> POSIX tools that requires EOL at EOF (e.g. git) wouldn't warn you and throw an error;

I've never seen such a warning from git or other tools I use. I should mention that we develop 1M+ lines of code project and never have any problem with EOLs since we stopped appending one file to another with `cat` and started using specialized building tools four years ago.

> Cons:
>    Need to configure .editorconfig file and install plugin for your IDE (you working in notepad, right?)?

What about "Plurality is not to be posited without necessity" rule?
This stupid rule comes from ancient days. Nobody really tested its necessity.
All the discussion lively reminds me famous experiment on monkeys — where finally nobody knows why really it's prohibited to do something, but still fiercely insists on keeping the rule.

**Comment by zxqfox** [comment]
> I vote for remove this rule from codestyle.

@zloylos Removing is even worse than an opposite. Here we should decide to use EOL at EOF or don't. Explicitly.

@tarmolov I know that Yandex codestyle is more common than BEM community, but [canonical version has this rule](https://github.com/bem/jscs-bem/blob/master/presets/canonical-bem.json#L30) and [new one based on Yandex jscs preset](https://github.com/bem/jscs-bem/blob/master/presets/bem.json#L2) that also has this rule. It means that some other guys will vote for this rule (I don't know if it weights anything for ya), just fyi.

**Comment by zxqfox** [comment]
> I've never seen such a warning from git or other tools I use.

It's not a problem ;-) Now you see:
![image](https://cloud.githubusercontent.com/assets/677518/6558205/d1b3deb8-c68b-11e4-9fbe-2fc7337bee00.png)

> and never have any problem with EOLs since we stopped appending one file to another with cat and started using specialized building tools four years ago.

I will agree with you when `git` will stop noticing me about this. I know just 99% of tools can handle this. But it's free to add this line automatically, so no reason to make `git` sad.

> What about "Plurality is not to be posited without necessity" rule?
> This stupid rule comes from ancient days. Nobody really tested its necessity.
> All the discussion lively reminds me famous experiment on monkeys — where finally nobody knows why really it's prohibited to do something, but still fiercely insists on keeping the rule.

Yep. And nope. See above. Risk of fail vs free adding EOL at EOF by editor — your choice is here.

Personally I really hate this message in git, and moreover I hate diffs that can't be resolved automatically at the EOF without EOL at EOF. That's my practical experience why we must use this rule. And it's in `git`. I don't even want to say about `svn`'s conflict resolver...

**Comment by ikokostya** [comment]
This rule helps us keep our sources in same style and removes redundant git diffs. Of course you need setup your editor, but only once.
