### ISSUE TITLE
Function declaration: space between function and parentheses

### ISSUE THREAD

**Issue by twirl** [ymaps/codestyle#21]
There are two contradicting rules:
```
function foo() {
    // ...
}

var bar = function () {
    // ...
};
```
In my opinion, there should be always a space before parentheses in function declaration.

**Comment by ikokostya** [comment]
Current rule is unambiguous: function keyword != function name.
Proposal looks weird.

**Comment by ikokostya** [comment]
There is one common rule: add whitespace after `function` keyword (like after any other keyword), not after function name.
