### ISSUE TITLE
Parentheses rule

### ISSUE THREAD

**Issue by twirl** [ymaps/codestyle#23]
Styleguide says: `Parentheses [...] Should be used only if it is required of the expression's syntax or semantics.`
In my opinion, parentheses should be always use to indicate logical meaning of expression. Redundant parentheses are good.

**Comment by ikokostya** [comment]
>  I see absolutely no problem in redundant parentheses.

We don't write `return(1)` or  `if ((x > 1)) {}`. Rule should be unambiguous.

**Comment by twirl** [comment]
That's still better than constructions like `return a - b > c && c || c + d && d + 1 || e` I saw a couple in jQuery code — it's awful, though, formally, there is no need in parentheses.
Hell, half of coders's never heard of De Morgan laws. Keeping parentheses will save you hours of debugging.

**Comment by ikokostya** [comment]
This rule from http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#Parentheses. Personally I have never had problems with parentheses.
