### ISSUE TITLE
When should a pr/issue be closed?

### ISSUE THREAD

**Issue by tarmolov** [ymaps/codestyle#27]
We have big discussions here. A good question is when we should stop and make a final decision.

Ideas? Suggestions?

**Comment by vtambourine** [comment]
Week after last comment author can summarise the discussion and make actions according to majority opinion. This is my suggestion.

**Comment by twirl** [comment]
Oh, that would be great.

**Comment by vtambourine** [comment]
@tarmolov, lets decide something. What is the point of having public codestyle and not accepting pull requests?

**Comment by dmikis** [comment]
One week is plenty of time to make a decision about an issue. I believe longer active discussions are just pointless. Moreover, if last comment of a discussion is older than one week, there is good chance nobody gives a damn about it. And we can just drop it.

**Comment by tarmolov** [comment]
I'm ok with your suggestion. Could you make a pr with `CONTRIBUTION.md`?
