### ISSUE TITLE
Codestyle for ES6

### ISSUE THREAD

**Issue by zloylos** [ymaps/codestyle#33]

**Comment by dmikis** [comment]
Well, first of all, it seems reasonable to abandon use of `var` and use only `let` and `const`.

Also, it hearts my eyes to see that people tend to overuse arrow function. This sometimes makes code utterly ugly. I suggest to limit it somehow.

And I believe proxies are just harmful. I suggest to prohibit them.

**Comment by lemmy-** [comment]
> Also, it hearts my eyes to see that people tend to overuse arrow function. This sometimes makes code utterly ugly.

Could you give an example of such code?

**Comment by ikokostya** [comment]
I think we should move discussion about `ES6` features to separate issues.

**Comment by ikokostya** [comment]
I think this issue can be closed, because we added basic rules for es6.
