### ISSUE TITLE
Spaces around comma

### ISSUE THREAD

**Issue by razetdinov** [ymaps/codestyle#60]
I propose adding these two rules:

    "disallowSpaceBeforeComma": true,
    "requireSpaceAfterComma": true

**Comment by ikokostya** [comment]
Yes, I have plan to check new `jscs` rules. Maybe later at this week.

**Comment by razetdinov** [comment]
OK, just in case created https://github.com/ymaps/codestyle/pull/61

**Comment by ikokostya** [comment]
fixed in https://github.com/ymaps/codestyle/pull/61
