### ISSUE TITLE
JSCS 3 support for loris preset

### ISSUE THREAD

**Issue by andre487** [ymaps/codestyle#65]
It has already released, but not supported by this preset

**Comment by andre487** [comment]
Sorry, wrong repo

**Comment by ikokostya** [comment]
`JSCS v3` hasn't breaking changes http://jscs.info/changelog#version-3-0-0-https-github-comjscs-devnode-jscscomparev2-11-0-v3-0-0-2016-04-14. Therefore I just bump max version in peer dependencies.

`+ jscs-preset-loris@1.2.0`

**Comment by andre487** [comment]
Thanks!
