### ISSUE TITLE
Class properties order

### ISSUE THREAD

**Issue by ikokostya** [ymaps/codestyle#84]
### General
In this issue I want to discuss about fields order in a class declaration.

### Public, private, and protected modifiers
Because most code users or readers are first interested in the public interface, not in the implementation details, make sense use the following order: `public`, `protected`, `private`. But there are some drawbacks:

* Private field declarations are placed at the end of a class, but constructor (where this fields are initialized) is placed at the beginning of a class. For big classes you need often scroll code up and down each time when you want to see variable type before initialization. In other words, distance between declaration and initialization of some field can be long, but we [prefer](https://github.com/ymaps/codestyle/blob/master/javascript.md#variable-declaration) keep it short:

  > Each variable should be declared as close as possible to the place where it's first used.

* TypeScript allow short field declaration:

  ```ts
  class Foo {
       constructor(private _bar: number) {}
  }
  ```
  instead

  ```ts
   class Foo {
       constructor(bar: number) {
            this._bar = bar;
       }

       // some code...
  
       private _bar: number;
  }
  ```
  
  Or allow initialize variable with declaration:

  ```ts
  class Foo {
      constructor() {
          // initialize other fields
      }
    
      // some code...

      private _map: Map<string, string> = new Map();
  }
  ```
  In this cases fields initialization is happen in different places.

### Static and non-static

Should `static` fields be placed before or after non-static fields?

**Comment by dmikis** [comment]
Order

```
public props;
constructor;
public methods;
protected props;
protected methods;
private props;
private methods;
```

seems to work OK for us. However, we don't use short field declarations.

**Comment by ikokostya** [comment]
@dmikis Where is a place of private constructor and static properties?

**Comment by dmikis** [comment]
Private constructor is between private props and methods, analogous to a public one.

Static props are always after non-static ones *within* access qualifier. I.e. public instance props, public static props, protected instance props, protected static props, etc.
