### ISSUE TITLE
Mandatory return type for functions and methods

### ISSUE THREAD

**Issue by dmikis** [ymaps/codestyle#94]
I suggest we add to the code style a requirement for functions and methods to always have return type specified explicitly. There're two points behind this.

1. Signature of a function (and of a method) is documentation for fellow developers. Thus, leaving it to the compiler to infer adds a burden on a human who reads your code to do the same job.
2. There's always a chance to get it plainly wrong with either a wrong guess (you meant one type, compiler inferred another) or break things later possibly in an ambiguous manner. I.e., let's say leave for the compiler to infer some types from function's return type that gets inferred itself. If it changes, compilation errors will arise from usage sights of those variables, not on call sights of the function.

**Comment by ikokostya** [comment]
I agree in general, but when I need implement some interface I often omit return type, because specify it in each implementation is little annoying.
