### ISSUE TITLE
Identifier references in object literals

### ISSUE THREAD

**Issue by dmikis** [ymaps/codestyle#95]
I suggest to add a rule that *requires* use of identifiers in object literals for ES6 and TS code:

```
// Bad:
{foo: foo}
{
    foo: computeFoo(),
    bar: bar,
    baz: 1
}

// Good:
{foo}
{
    foo: computeFoo(),
    bar,
    baz: 1
}

**Comment by vmit** [comment]
I would not agree: using mixed syntax "breaks" your "scanning/reading patterns" and the shortened property look like something requiring your attention. Plus it has to be managed manually when you feractor a property/variable
BTW: literals with all identifier-properties looks really nice

**Comment by ikokostya** [comment]
1. This rule can be applied to JavaScript style guide too (`ts` extends `js` style guide).
2. Personally I **use** shorthand properties, because I read its faster: 

2 steps:

```
{bar: bar}
 ^-------------- 1) object has property `bar`
      ^--------- 2) which has value `bar`. There is additional attention, because value can be different.
```

vs 1 step:

```
{bar}
 ^-------------- 1) object has property `bar` with the same value.

**Comment by sergets** [comment]
I vote for this rule, we use it in our styleguide and I found out it helps maintain single terminology throughout the application.

`{ id, geoObject, date, label: caption }` bends you towards choosing the right word between `label` and `caption` much stronger than `{ id: id, geoObject: geoObject, date: date, label: caption }`

**Comment by dmikis** [comment]
@ikokostya The question is do we use them everywhere possible or only when **all** properties of an literal are expressible that way?

**Comment by ikokostya** [comment]
@dmikis Whenever possible.
