### ISSUE TITLE
Template parameter naming

### ISSUE THREAD

**Issue by dmikis** [ymaps/codestyle#96]
There've been a discussion around our [current naming rules](https://github.com/ymaps/codestyle/blob/f188d3afcf9d6af31d554f631f2466d88d12e8fa/typescript.md#naming) for templates. @vmit suggests (IIUC) to adopt a rule that will allow to distinguish a template parameter in code.

The main concern is naming conflicts for constrained template parameters, i.e. the ones required to extend a type or implement a interface:

```
interface StyleExtractor<S extends Style> {
    (...args: any[]): S;
}
```

Here's `S` is a violation of our style guide. But it's difficult to come up with an alternative since the most sane one is `Style` but it's already taken:( In this particular example we can rename `Style` in import statement, but that's not a universal solution.

During discussion we've looked at some other codebases and code styles to gather more input. Here's the findings:

1. STL [seems](http://en.cppreference.com/w/cpp/container/vector) [to use](http://en.cppreference.com/w/cpp/algorithm/for_each) rules analogous to ours;
2. Java [suggest](https://docs.oracle.com/javase/tutorial/java/generics/types.html) to **always** name generic parameter with a single letter (but there're several violations of this rule in the JDK);
3. Google's Java style guide [suggests](https://google.github.io/styleguide/javaguide.html#s5.2.8-type-variable-names) to either use single letter names or append `T` to name of a parameter (but the one for C++ [doesn't](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules));
4. after quick glance TSC itself seems to use somewhat Hungarian notation, either just `T`, `U`, etc or `TType`.

**Comment by dfilatov** [comment]
I'd vote for `TType` notation cause it:
  * explicitly declares there's a template parameter
  * doesn't introduce ugly single-letter naming, especially for multiple parameters

**Comment by ikokostya** [comment]
I like Google's Java style guide with ending `T` (e.g. `FooT`)
* it looks nice
* avoid name conflicts with interfaces (`StyleT extends Style`)
* and easy to read as `Foo Type`

Leading `T` looks awkward, but consistently with other notations with leading letters, e.g. `I` for interfaces. Of course, if we decided to use them.

**Comment by dmikis** [comment]
After some consideration I've ended up preferring Google's option too. My motivation is that `TFoo` is a clear homage to Hungarian notation and adopting that approach will raise a (rather incovinient:) question: why not do that everywhere. Whereas `FooT` may be considered as shortened version of `FooType` which makes sense for generic parameters.

**Comment by vmit** [comment]
I'm fine with the T postfix too

**Comment by dmikis** [comment]
The PR was met with some friction. My understanding is that we have a consensus on necessity of suffix *or* prefix, we just need to choose one. Since that choice is purely stylistic I suggest we vote for it.

To make it easy we'll do that with comment reactions. React with 👍 to vote for `TGenericParamter` and 👎 for `GenericParameterT`.

Motivation for `TGenericParameter`:

> Looks more consistently with `IInterface` if a project chooses to adopt it and with prefix `_` for private and protected properties.

Motivation for `GenericParameterT`:

> Easily reads as `Generic Parameter Type`, don't suggest usage of Hungarian notation (which we try to avoid).

/cc @dfilatov @ikokostya @vmit @makishvili @tarmolov @dodev @twoRoger

**Comment by ikokostya** [comment]
Why need explicitly specify that name is template parameter?

**Comment by dmikis** [comment]
> Why need explicitly specify that name is template parameter?

My best understanding is that it's convenient to distinguish them from all the other types in a module. However, adding something to a parameter name gives as a simple and reliable naming scheme that avoids conflicts.

**Comment by ikokostya** [comment]
After thinking some time, I can't make decision. I don't like *required* prefix or suffix for template parameters, but it can be used as ad hoc solution for original problem:

```ts
interface StyleExtractor<StyleType extends Style> {
    (...args: any[]): S;
}

// or

interface StyleExtractor<TStyle extends Style> {
    (...args: any[]): S;
}
```

So, for now I vote for don't specify this rule in style guide. Each project can select own way for solving this problem.
