### ISSUE TITLE
Add rule for spaces in imports 

### ISSUE THREAD

**Issue by ikokostya** [ymaps/codestyle#97]
**Good**

```js
import {foo, bar} from './foo';
```

**Bad**

```js
import { foo, bar } from './foo';
```

Like in [objects](https://github.com/ymaps/codestyle/blob/master/javascript.md#objects) and [destructuring assignment](https://github.com/ymaps/codestyle/blob/master/javascript.md#destructuring-assignment).

**Comment by flapenguin** [comment]
I personally like how version with spaces visually separates imported names.

TSLint has rule for both: https://palantir.github.io/tslint/rules/import-spacing/

**Comment by ikokostya** [comment]
> I personally like how version with spaces visually separates imported names.

Names separated by space

```js
import {foo, bar} from './foo';
```

There is no spaces after `{` and before `}`. 
Fixed issue description.
