### ISSUE TITLE
Ternary operator

### ISSUE THREAD

**Issue by flapenguin** [ymaps/codestyle#98]
Current style does not allow easy chaining and makes it hard to visually see then/else branches when latter are longer then 20 symbols.

**Long lines**
(current codestyle)
```js
var result = someLong || butNot || veryComplicated || condition ?
    some + pretty + long + but + simple + expression :
    fallback;
```

vs

(proposed)
```js
var result = someLong || butNot || veryComplicated || condition
    ? some + pretty + long + but + simple + expression
    : fallback;
```

`?` and `:` immediately attract attention.

**Chaining**

Chaining ternary operator is a nice feature for small inline multi-condition choosing:

(current coodestyle)
```js
var value = /blah/.test(x) ?
  'blah' :
  /foo/.test(x) ?
  'foo' :
  /bar/.test(x) ?
  'bar' :
  'nope';
```

(proposed)
```js
var value = /blah/.test(x) ? 'blah' :
  /foo/.test(x) ? 'foo' :
  /bar/.test(x) ? 'bar' :
  'nope';
```

**Comment by ikokostya** [comment]
At first glance I can found two pros for current style:

* Easy maintain from simple to complex expressions:

  ```js
  // b and c are simple
  var x = a ? b : c;

  // b and c are bit complex. 
  var y = a ?
      longButSimpleOperandB : longButSimpleOperandC;

  // b and c are complex
  var z = a ?
      moreComplicatedB :
      moreComplicatedC;
  ```

  It helps to reduce diff size. Just add `\n` in every case.

* Consistent with rules about placing operators on the same line, e.g. `&&` or `+` operators. In this case one common style is easier for remember.

**Comment by ikokostya** [comment]
For chaining I propose the following style:

```js
var value = /blah/.test(x) ? 
   'blah' :
    /foo/.test(x) ? 
       'foo' :
       /bar/.test(x) ?
          'bar' :
          'nope';
```

But I think expressions like this should be avoided. Maybe use temporary variable with meaningful names for readability.

**Comment by dmikis** [comment]
I oppose suggested changes. Here's why:

* **long lines** — that for me basically falls under the same category as "comma-first" rules, i.e. somewhat unnatural way to format a text (even if it is for a machine);
* **chaining** — if you fix the first example to follow current rules, it'll be completely readable, whereas proposed way is too cluttered due to unnecessary stinginess with code lines (they're free after all).
